name: Publish to AUR

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt -Sy base-devel git

      - name: Setup SSH for AUR
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

      - name: Build and push to AUR
        run: |
          git clone ssh://aur@aur.archlinux.org/shard-cli.git
          cd shard-cli
          cp ../PKGBUILD ./
          makepkg --printsrcinfo > .SRCINFO
          git add PKGBUILD .SRCINFO
          git commit -m "Update to ${{ github.event.release.tag_name }}"
          git push origin master
